### ISSUE TITLE
Confirm Headset Quaternion message works

### ISSUE THREAD

**Issue by mungewell** [RiftCat/vridge-api#17] opened 2018-11-07 19:23 UTC
I'm attempting to script (1) against the API, however I as seeing different pose motion when sending via Euler angles compared to send as Quaternion.

Can someone confirm the API is correct on the Headset Quaternion message?
https://github.com/RiftCat/vridge-api/wiki/Head-Tracking-API
![vridge_api_send_quaternion](https://user-images.githubusercontent.com/236907/48155235-c77b2980-e287-11e8-88c5-e5d303c9f00b.png)

1. https://github.com/mungewell/pyPSVR/blob/master/example4_vridge_sensors/vridge_psvr.py

**Comment by balukin** [comment] 2018-11-08 12:53
Hi

Can you provide example data and expected result vs actual result so I can verify it?
1) Yaw-pitch-roll representation
2) Quaternion representation equivalent to (1). https://quaternions.online may be a good way to verify it
3) If possible - explanation which one seems to be correct and which one isn't. Maybe a screenshot?

We're making quite a lot of tracking changes in 2.3 (to be available within few weeks) so I'll be able to check if it's the same in 2.3.

**Comment by mungewell** [comment] 2018-11-08 17:15
Hi,
Thanks for the response. Late last night I actually got system operating with Euler angles and Quaternion visually the same - by swapping the roll and pitch Euler angles and messing with gyro/acc axis to get the AHRS functional.
https://github.com/mungewell/pyPSVR/blob/master/example4_vridge_sensors/vridge_psvr.py#L218
```
		(p,r,y) = ahrs.quaternion.to_euler_angles()
		data = tuple((p,y,r)) + position
```

But I believe that there's a error somewhere in the code (either Quaternion lib or VRidge) as the pitch/yaw/roll extracted from the Quaternion should be correct (without the need for these 'hacks')

The quaternion lib returns the order as follows, computed a few lines above from **same** quaternion that I am sending to Vridge
https://github.com/mungewell/pyPSVR/blob/master/example4_vridge_sensors/quaternion.py#L93
```
return roll, pitch, yaw
```

I'll review your links tonight and maybe upload some debug prints (though these slow the system down a lot and the tracking doesn't really work with them).

**Comment by balukin** [comment] 2018-11-08 18:11
It might be an error in our interpretation. We can check expected vs actual data if you provide few example data points but it might be also caused by misinterpretation of yaw-pitch-roll representation.

Euler angles can have multiple representations that use different orders of axis rotation. Gaming mostly uses yaw-pitch-roll that are actually Tait–Bryan angles. Proper Euler angles could likely result in pitch/roll being mixed if they were misinterpreted as Tait-Bryan angles.

Wikipedia:
> Without considering the possibility of using two different conventions for the definition of the rotation axes (intrinsic or extrinsic), there exist twelve possible sequences of rotation axes, divided in two groups:
>
> Euler angles are typically denoted as α, β, γ, or φ, θ, ψ. Different authors may use different sets of rotation axes to define Euler angles, or different names for the same angles. Therefore, any discussion employing Euler angles should always be preceded by their definition.
> 
> Without considering the possibility of using two different conventions for the definition of the rotation axes (intrinsic or extrinsic), there exist twelve possible sequences of rotation axes, divided in two groups:
> 
> Proper Euler angles (z-x-z, x-y-x, y-z-y, z-y-z, x-z-x, y-x-y)
> Tait–Bryan angles (x-y-z, y-z-x, z-x-y, x-z-y, z-y-x, y-x-z).
> 
> Tait–Bryan angles are also called Cardan angles; nautical angles; heading, elevation, and bank; or **yaw, pitch, and roll**. Sometimes, both kinds of sequences are called "Euler angles". In that case, the sequences of the first group are called proper or classic Euler angles.

https://en.wikipedia.org/wiki/Euler_angles

I checked the math lib that you are using. It has two functions - [to_euler_angles](https://github.com/morgil/madgwick_py/blob/master/quaternion.py#L82) and [to_euler123](https://github.com/morgil/madgwick_py/blob/master/quaternion.py#L95)
Since we're using yaw-pitch-roll and not "proper" Euler, it seems that you should call this one
```
 def to_euler123(self):
        roll = np.arctan2(-2*(self[2]*self[3] - self[0]*self[1]), self[0]**2 - self[1]**2 - self[2]**2 + self[3]**2)
        pitch = np.arcsin(2*(self[1]*self[3] + self[0]*self[1]))
        yaw = np.arctan2(-2*(self[1]*self[2] - self[0]*self[3]), self[0]**2 + self[1]**2 - self[2]**2 - self[3]**2)
        return roll, pitch, yaw
```
as this one matches matches yaw-pitch-roll conversion formula from [Wikipedia](https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions#Quaternion_%E2%86%92_Euler_angles_(z-y%E2%80%B2-x%E2%80%B3_intrinsic)).

Note: I might be wrong, let me know if I am. It's easy to make a mistake during conversions between rotation representations.

**Comment by balukin** [comment] 2018-11-08 18:19
Also, just to make it clear with https://quaternions.online/.

It uses Three.js lib to handle the math which internally [also uses](https://threejs.org/docs/#api/en/math/Euler.order) Tait-Bryan.

**Comment by mungewell** [comment] 2018-11-11 16:45
I added code to initilise the AHRS with a particular vector, and then without updating the position, I dumped the Euler, Euler123 and Quaternion values.
```
refq = Quaternion(1,0,0,0) # look front
#refq = Quaternion.from_angle_axis(np.pi/2,0,0,1) # look front, sideways
#refq = Quaternion.from_angle_axis(np.pi/2,1,0,0) # look up
#refq = Quaternion.from_angle_axis(np.pi/2,0,1,0) # look right
ahrs = MadgwickAHRS(sampleperiod=0.0005, beta=.5 , quaternion=refq)
...
	if options.debug:
		print("Euler: ", ahrs.quaternion.to_euler_angles())
		print("Eu123: ", ahrs.quaternion.to_euler123())
		print("Quat:  ", ahrs.quaternion._get_q())
		print()
```


```
refq = Quaternion(1,0,0,0) # look front
Euler:  (0.0, 0.0, 0.0)
Eu123:  (0.0, 0.0, 0.0)
Quat:   [1 0 0 0]

refq = Quaternion.from_angle_axis(np.pi/2,0,0,1) # look front, sideways
Euler:  (0, 1.5707963267948966, 0.0)
Eu123:  (-0.0, 0.0, 1.5707963267948963)
Quat:   [ 0.70710678  0.          0.          0.70710678]

refq = Quaternion.from_angle_axis(np.pi/2,1,0,0) # look up
Euler:  (1.5707963267948963, 0.0, 0.0)
Eu123:  (1.5707963267948963, 1.5707963267948966, -0.0)
Quat:   [ 0.70710678  0.70710678  0.          0.        ]

refq = Quaternion.from_angle_axis(np.pi/2,0,1,0) # look right
Euler:  (0.0, 0.0, 1.5707963267948963)
Eu123:  (-0.0, 0.0, -0.0)
Quat:   [ 0.70710678  0.          0.70710678  0.        ]
```

So it looks like there's something funky with the code I 'borrowed'. Will look to see if I can spot the mistake.

**Comment by balukin** [comment] 2018-11-13 16:38
Judging by the YT video, I see that you've got some promising results already. 

How's the framerate inside the headset? Lack of reprojection probably causes few frames skips here and there but the latency should be quite good.

We're gonna give your solution some exposure, if that's okay.

**Comment by mungewell** [comment] 2018-11-13 17:40
Yes the results are promising, although I did see some issues:
1). Motion in the 'construct' (empty VR world with lines) shows two lines/ghosting and stabilize to proper image when stationary. 
2). Latency on separate PC across WiFi network was pretty high. MUCH better with local script.

Not sure whether 1). is sensor/data related, or render related. I suspect that there are many settings within VRidge app (there are parameters in it's config), are these documented somewhere? Have tinkered with chromatic distortion to improve the image quality.

Happy for you to publicize, the main purpose of project is to get people interested in tinkering. Hence why using Python and the 'DIY' aspect.


On the axis, they are still jumbled. I switched to another Quaternion codebase, which implicitly states it is using Tait-Bryan angles:
https://github.com/KieranWynn/pyquaternion/blob/master/pyquaternion/quaternion.py#L965

Took Pitch-Yaw-Roll as 'truth' and then jumbled the Quaternion axis until the image matched.
```
		# Send as Quaternion (note: VRidge params switched)
		(w,x,y,z) = ahrs.quaternion.elements
		data = tuple((y,z,x,w))+ position
		output = quaternionposition.build(dict(data=list(data)))
```

**Comment by mungewell** [comment] 2018-11-13 19:59
On framerate - You ask 'in headset', but note that the PSVR does not render itself - the PC does all rendering and outputs 1080P60 (nominal, unless you patch the EDIDs to render at 120Hz).

I have access to an HDMI recorder at work. Will use in attempt to understand what it happening wrt ghosted lines.

**Comment by balukin** [comment] 2018-11-14 13:32
> 1). Motion in the 'construct' (empty VR world with lines) shows two lines/ghosting and stabilize to proper image when stationary.
> I have access to an HDMI recorder at work. Will use in attempt to understand what it happening wrt ghosted lines.

This should shine some light on it. We sometimes test with high speed recordings to debug problems hard to understand without slow-motion.  StreamView basically copies the texture captured from SteamVR (when SteamVR submits it to HMD driver) so it's probably not distorted inside the frame but may by related to synchronization with display. StreamView doesn't VSync so maybe it's vertical tearing visible on non-60Hz screen but not visible on 60 Hz. StreamView was mostly designed for Gamestream+Moonlight which locks the screen to 60 FPS.

>  I suspect that there are many settings within VRidge app (there are parameters in it's config), are these documented somewhere? Have tinkered with chromatic distortion to improve the image quality.

StreamView params are documented here:
https://support.riftcat.com/hc/en-us/articles/115005811189-Moonlight-Advanced-Guide
More specifically, our distort shader is based on [this one](https://github.com/fre-sch/sweetfx-vr-sbs/blob/master/Custom.h) with some tweaks.

As for the framerate - yes, I was thinking about perceivable smoothness. On the mobile side we have the benefit of another GPU post processing the final frame (which also re-projects the image, reducing latency and increasing smoothness). StreamView doesn't have that but lack of reprojection should be countered by way lower latency - at least theoretically.

Quaternions and orientation systems is something I'd like to investigate later when 2.3 is in beta. We're very close to releasing it soon (~2-4 weeks - date is not set yet).

**Comment by balukin** [comment] 2019-02-01 17:17
Marking it as resolved because this discussion drifted away from original problem and we have made quite a lot of changes to rotational data processing. If anyone finds anything incorrect, please leave a comment with input and expected output so we can fix incorrect math.

**Closed as completed by balukin** 2019-02-01 17:17 UTC
